[client]
showThemeSettings = false

[theme]
base="dark"
primaryColor="#0033cc"   #the buttons, bar collor
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#ffffff"
textColor="#ffffff"
font="sans serif"


