[theme]
base = "dark"
primaryColor = "#00ccff"  # bright cyan/blue
backgroundColor = "#0a0f1c"  # deep navy-blue
secondaryBackgroundColor = "#1a2238"  # bluish shadow
textColor = "#d8faff"  # soft neon blue
font = "sans serif"

[client]
showThemeSettings = false

